### ISSUE TITLE
"Upload error necessary data rewind wasn't possible"

### ISSUE THREAD

**Issue by Shuudoushi** [linuxgurugamer/CraftImport#1]
I just need to know if this is a bug, or if i broke something... Thanks.

![Imgur](http://i.imgur.com/7EdVZck.png)

**Comment by linuxgurugamer** [comment]
The mod encountered a problem uploading to KerbalX, that is the error from KerbalX.
Please send me your craft file (and a list of mods, if possible), I'll see if I can reproduce it.
I assume you did this more than once?

**Comment by Shuudoushi** [comment]
Many more times yes. Give me a sec to put together a zip for you.

**Comment by Shuudoushi** [comment]
May be more than a 'sec'. I wasn't expecting you to get back to me so quickly so I was trying with another craft that did work to see if the issue persisted...

**Comment by Shuudoushi** [comment]
Here we are: http://puu.sh/n63Gx/68c5184253.zip

**Comment by Shuudoushi** [comment]
I can confirm that [this craft](https://kerbalx.herokuapp.com/Shuudoushi/BRF-22-GA-Storm) (which uses custom parts made by me) uploaded just fine, but the other two craft (which don't have my custom parts on them) throw that error.

**Comment by Shuudoushi** [comment]
Oh... Hey @linuxgurugamer... I found the issue... https://kerbalx.herokuapp.com/imgur_image_problem

Seems a temp work around is a different URL for kerbalx, so the way craftimport uploads craft is going to be broken for a bit until the mess with imgur straightened out...

**Comment by Shuudoushi** [comment]
Since I made this issue, I'm going to use to see about helping you out with the plain text passwords. If you can point me to the bit of code that saves and recovers the password, I'll be digging out my MIT licensed SHA256 lib.

**Comment by Shuudoushi** [comment]
Hmmm, I can't find my SHA lib... But I did find this one on github under MIT, https://github.com/yuriks/SHA2-Csharp

**Comment by linuxgurugamer** [comment]
I'm a bit puzzled, what are you offering to help with?

**Comment by Shuudoushi** [comment]
How the KerbalX login info is saved as plain text. You can use that SHA256 lib to save it as a hash instead.

**Comment by linuxgurugamer** [comment]
Ah, ok.
The data is saved in the file util/FileOperations.cs.  It is stored in the CI_Settings.cfg file

**Comment by Shuudoushi** [comment]
Ok, and you are using just straight C# right?

**Comment by linuxgurugamer** [comment]
yes
