### ISSUE TITLE
Mono garbage generation 

### ISSUE THREAD

**Issue by SpaceFoon** [linuxgurugamer/CraftImport#2]
Only in VAB/SPH this mod causes the mono heap to steadily grow until it's full. After that garbage collector runs every second for about half a second. I have reproduced this on an AMD and an Intel system with all sorts of different mod setup and on a stock + Memgraph install. Also it doesn't matter what you are doing as long as the VAB/SPH is loaded the problem will be no worse or better.

**Comment by linuxgurugamer** [comment]
Just curious, are you on Windows or Linux or Mac?

**Comment by SpaceFoon** [comment]
Should have said Windows 10 and 7. I could test on an old Mac if you think that would help.

Also I have never submitted a bug report before so if you need any more info I'm glad to help.

**Comment by HebaruSan** [comment]
I saw this on Linux and posted [a MemGraph screenshot](http://forum.kerbalspaceprogram.com/index.php?/topic/139128-12x-memgraph-1103-with-stutter-reduction/&do=findComment&comment=2914636) on the forum. Padishar had some observations about what kind of code patterns might be responsible.

**Comment by linuxgurugamer** [comment]
Thank you all, I'm going to merge @HebaruSan change.
I have been busy on other project, was just getting to this and saw the PR
